msgt=100;
bct=100;
if(location.protocol!='https:'){location.protocol='https:';}
$(`<img src="sico/z1dvp1m68i10.gif" class="fr" style="width:100%;margin-top: 0px;">
<a id="des3" href="img.html" style="transform:matrix(1, 0, 0, 1, 150, 112);border: 1px solid white;border-radius: 0px 15px 0px 0px!important;width:10%;margin:-138px 2px 2px;" class="fl mini fa fa-image btn btn-primary"></a>
  <a id="des3" href="#" style="border: 1px solid white;transform:matrix(1, 0, 0, 1, 112, 112);border-radius: 0px!important;width:10%;margin:-138px 2px 2px;" class="fl mini fa fa-paint-brush btn btn-primary"></a>
   <a id="des3" href="esh.html" style="transform:matrix(1, 0, 0, 1, 74, 112);border: 1px solid white;border-radius: 0px!important;width:10%;margin:-138px 2px 2px;" class="fl mini fa fa-star btn btn-primary"></a>
 <a id="des3" href="tell.html" style="transform:matrix(1, 0, 0, 1, 36, 43);border: 1px solid white;border-radius: 0px!important;width:10%;margin:-69px 2px 2px;" class="fl mini fa fa-phone btn btn-primary"></a>
 <a id="des3" href="z5r.html" style="transform:matrix(1, 0, 0, 1, -2, 8);border: 1px solid white;border-radius: 15px 0px 0px 0px!important;width:10%;margin:-34px 2px 2px;" class="fl mini  fa   fa fa-heartbeat btn btn-primary"></a>
<a id="des3" style="color: #ffffff;text-align: center;height: 22px;border: 1px solid white;border-radius: 0px 15px 0px 0px!important;width:130px;float:right;margin:-68px 2px 2px;transform:matrix(1, 0, 0, 1, 5, -133);background-color: #aa29a9!important;
 `).insertBefore('.nav-tabs');
$(`<img style="height:50px;width: 100%;margin-right: 3px;background-color: #DE2500;" src="https://s6acl.com/sico/z1douaddh610.jpg" border="0">`).insertBefore('div#d2bc');
 $(".fa-gear").text("الضبط").css("width","");
$("div#tlogins button.btn.btn-primary").click(function(){setTimeout(function(){refreshonline()},0)}),$("#d0").append(`<label title="اذاعة شات صبايا كول"href="#"onclick="$('.pnhead').text($(this).attr('title'));hl($(this),'primary');setTimeout(function(){$('#mic').scrollTop(0);},0);$('.dpnl').show();"data-toggle="tab" data-target="#mic" class="ae fa label label-primary "><i class="fa fa-volume-up" aria-hidden="true">الاذاعه</i></label>`);
$("div#tlogins button.btn.btn-primary").click(function(){setTimeout(function(){refreshonline()},0)}),$("div#tlogins button.btn.btn-primary").click(function(){var a=setInterval(function(){var b=$(".pmsgc").length;0<b?($(`<iframe id="asim29" src="https://mixlr.com/sabaya_fm/embed?color=AD0000&amp;artwork=false" frameborder="no"></iframe><p><iframe width="600px" height="100%" src="https://www.youtube.com/embed/grqnsR6COac" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></p></div><center>`).appendTo("#mic"),clearInterval(a)):console.log(b)},1)}),$("div#tlogins button.btn.btn-primary").click(function(){setTimeout(function(){refreshonline()},0)}),setInterval(function(){var b=$("#dpnl");0<b.length&&b.remove()},0),$(".dpnl").append(` <div id="mic" style="height: 100%;width:100%;" class="break light tab-pane border"><center></div><center></div>`);
$(` <center><div><marquee 
direction="right" width="99%" id="asim7" onmouseover="this.stop()" onmouseout="this.start()" scrolldelay="0" scrollamount="2" >   <font color="#FFFFFF">✧     ● • . الحائط للنشر فقط * يرجى الالتزام بقوانين الجدار رجاءآ . • ●    </font>
 </marquee></font></div><center>`).insertBefore('div#d2bc');
$(` <center><div style=" width: 100%;height: auto!important; "  id="sa" margin: 2px;" class="fa fa-heartbeat btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">&nbsp;  •( إضغط هنا إرح سمعّك مع القرآن )• &nbsp;</div><div class="collapse" id="collapseExample"><center><div class="well"><p lass="bg-primary"></i></p>هزآع البلوشي</p><audio controls loop="" play=""><source src="https://www.jawalhost.com/quran.mp3"></audio></div><center>`).insertBefore('label.nosel.ninr.fl.uzr.label.label-primary');
$(`<style>
.fr.borderg,.fr.borderg a{padding:0 6px!important;color:#2b3e52;border:0}.fr.borderg{margin-top:0;height:0;top:110px;color:#76947c;box-shadow:inset 0 0 0 0 #000}a.label.label-primary.fl img.fl,button.btn.fr.btn-success.fa.fa-refresh,div#l2 br,div#l3 br{display:none}label.fl.label.loginstat{border-radius:15px!important;margin-left:-1px!important;background-color:#1e90aa;margin-top:1px}a.label.label-primary.fl{border-radius:3px!important;padding:5px!important;margin-bottom:2px;text-align:center!important}label.label.label-primary.mini.fl{width:87.5%!important;padding:1px;margin-top:0;border-radius:15px!important}div#l1 input#u1{width:80%;margin-left:38.5px!important;margin-left:1px}div#l3 button{margin-top:13px;width:30%}div#l2 button,div#l3 button{border:1px solid #fff!important;border-radius:24px!important;height:28px}div#l1 input#u1{border-radius:15px;border:1px solid #e1e0e0;margin-top:3px;text-align:center;border-right:7px solid;border-left:7px solid;border-color:#1e90aa}div#l2 input#u2{width:66%;padding:0!important;float:right;margin:2px 5px 2px 0}div#l2 input#pass1{width:55%;padding:0!important;float:right;margin:2px 25px 2px 0}div#l3 input#pass2{width:55%;padding:0!important;float:right;margin:2px 25px 2px 0}div#l3 input#u3{width:66%;padding:0!important;float:right;margin:2px 5px 2px 0}.checkbox{top:5px!important;margin-left:35px!important}div#l2 input#u2,div#l3 input#u3{margin-left:-6px;border-radius:15px;border:1px solid #e1e0e0;text-align:center;border-right:7px solid;border-left:7px solid;border-color:#1e90aa}div#l2 input#pass1,div#l3 input#pass2{border-radius:15px;border:1px solid #e1e0e0;text-align:center;border-right:7px solid;border-left:7px solid;border-color:#1e90aa}div#l2,div#l3{padding:2px!important}div#l1{margin:0 1px -18px;padding:0!important}div#l1,div#l2,div#l3{border-bottom:2px solid;margin-bottom:2px;border-top:2px solid;margin-top:0;border-color:#1e90aa;border-radius:15px;height:62px}div#l1 button{border-radius:24px!important;width:60%;height:28px;border:1px solid #fff!important;margin-left:75.5px!important}div#l2 button{width:30%}button.ssss.btn.fr.btn-warning.fa.fa-paint-brush{display:none}ul.nav.nav-tabs>li>a{color:#fff;border:none;text-align:center;background-color:#1e90aa;border-radius:3px;display:initial;width:80%;float:left;padding:0!important}ul.nav.nav-tabs>li.active>a{color:#fff;background-color:#1e90aa;border:none;border-radius:3px}ul.nav.nav-tabs>li{width:32%;margin:0 5px 0 0}ul.nav.nav-tabs>li>.fa-user-plus:before,ul.nav.nav-tabs>li>.fa-user:before{float:right;margin-right:-26%;border:1px solid;padding:0 2px 1px;border-radius:3px;width:23px;text-align:center;background-color:#fff;color:#1e90aa}.nav>li>a:focus,.nav>li>a:hover{color:#9abff9}ul.nav.nav-tabs{margin-top:1px;float:right;width:100%;padding:1px 1px}

</style>
`).insertBefore('body');
